### ISSUE TITLE
ROM folder structure

### ISSUE THREAD

**Issue by RobLoach** [escalade/LibreELEC.tv#17]
Currently, the rom folder is structured with shortnames of the related consoles:

```
roms/bios
roms/nes
roms/snes
roms/genesis
roms/psx
```

I'd like to propose switching it to match the names of [what's in libretro-database](https://github.com/libretro/libretro-database/tree/master/rdb):

```
roms/Nintendo - Nintendo Entertainment System
roms/Sega - Mega Drive - Genesis
roms/Sony - PlayStation
```

It will clean up the roms directory a bit. Thoughts?

**Comment by escalade** [comment]
My thoughts are spaces and dashes in files/folders complicate things when scripting and will likely create issues with launching games. I might consider it once RetroArch cover enough platforms and I can drop Emulationstation.

**Comment by escalade** [comment]
roms/nintendo_entertainment_system
roms/sega_mega_drive
roms/sony_playstation

Was thinking that might be somewhat better. Not sure if's worth it though, the paths would need to be updated manually in filesystem and es_systems.cfg after upgrading.

**Comment by RobLoach** [comment]
Yeah, not worth it. While it does bring some clarify, the benefits are pretty low.
