### ISSUE TITLE
cffi:host

### ISSUE THREAD

**Issue by thoradia** [escalade/LibreELEC.tv#18]
I am trying to build cffi:host from this fork with LE 7.90.007.
It builds and runs for RPi2.arm.
But it fails to build for Generic.x86_64, with the following error:
```
/usr/bin/ld: cannot find /lib/libc.so.6
/usr/bin/ld: cannot find /usr/lib/libc_nonshared.a
/usr/bin/ld: cannot find /lib/ld-linux-x86-64.so.2
collect2: error: ld returned 1 exit status
error: command '/home/thoradia/Projects/thoradia/build.LibreELEC-Generic.x86_64-8.0-devel/toolchain/bin/host-gcc' failed with exit status 1
```
I tried many different CFLAGS/LDFLAGS, but everything failed.
Have you been able to successfully build cffi:host for Generic.x86_64?
If so, what is LE 7.90.007 missing?

**Comment by thoradia** [comment]
I works like this:
https://github.com/thoradia/LibreELEC.tv/blob/thoradia/packages/thoradia/couchpotato/cffi/package.mk

**Comment by 5schatten** [comment]
@thoradia 
You still have a clue what the fix was? Unfortunately your link isn't accessible anymore:

https://github.com/thoradia/LibreELEC.tv/blob/thoradia/packages/thoradia/couchpotato/cffi/package.mk

I'm facing the same problem, solved it by creating some symlinks but I guess there's a better way to solve it?  

`/usr/bin/ld: cannot find /usr/lib/libc_nonshared.a collect2: error: ld returned 1 exit status`

The whole output:

```
/home/5schatten/le82e/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.2-devel/toolchain/bin/host-gcc -shared -Wl,-rpath,/home/5schatten/le82e/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.2-devel/toolchain/lib -L/home/5schatten/le82e/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.2-devel/toolchain/lib -I/home/5schatten/le82e/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.2-devel/toolchain/include/python2.7 -O2 -Wall -pipe -I/home/5schatten/le82e/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.2-devel/toolchain/include -Wno-format-security build/temp.linux-x86_64-2.7/c/_cffi_backend.o -L/home/5schatten/le82e/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.2-devel/toolchain/lib -L/home/5schatten/le82e/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.2-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib -lffi -lpython2.7 -o build/lib.linux-x86_64-2.7/_cffi_backend.so
/usr/bin/ld: cannot find /usr/lib/libc_nonshared.a collect2: error: ld returned 1 exit status
error: command '/home/5schatten/le82e/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.2-devel/toolchain/bin/host-gcc' failed with exit status 1
Makefile:12: die Regel für Ziel „image“ scheiterte
make: *** [image] Fehler 1
5schatten@mintbs ~/le82e/LibreELEC.tv $ locate libc_nonshared.a
/home/5schatten/le82e/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.2-devel/glibc-2.27/.x86_64-libreelec-linux-gnu/libc_nonshared.a
/home/5schatten/le82e/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.2-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libc_nonshared.a
/usr/lib/x86_64-linux-gnu/libc_nonshared.a
```

**Comment by thoradia** [comment]
This is how I used to build cffi with the vanilla LibreELEC toolchain: https://github.com/thoradia/LibreELEC.tv/blob/backup-thoradia-8.2/packages/thoradia/depends/python/cffi/package.mk
I hope this helps

**Comment by 5schatten** [comment]
Thx a lot! :-) 

I try to make escalades remix buildable at linux mint without some system hacks, I'll try it. I suspect the build tools look for the libs in the wrong directory i.e. /usr/lib or /lib insteand of the buildroot and so it fails if you dont create some symlinks.
It works fine on my Arch VM so I know it's not escalades fault so let's tweak the system 👍 

EDIT: I'v deleted the symlinks and it still builds fine. Looks like this was the solution.
