### ISSUE TITLE
 Build fails on fbalpha-libretro

### ISSUE THREAD

**Issue by FREEZX** [escalade/LibreELEC.tv#19]
Hi.
I'm trying to build the project, but build always fails on building fbalpha-libretro, looks like it cannot find stdc++ for some reason:
http://pastebin.com/pxnqDW3V

**Comment by escalade** [comment]
Try modifying the package.mk to use platform=armv6 instead of platform=rpi. The libretro makefile doesn't define an "rpi" platform.

**Comment by FREEZX** [comment]
Cool, that fixed it.
Fixed all the issues i encountered and submitted pull request #20
