### ISSUE TITLE
Last commit not building, htop not finding libncurses

### ISSUE THREAD

**Issue by FREEZX** [escalade/LibreELEC.tv#21]
Tried to build  4e19031, got this error:
http://pastebin.com/2UQKQWqx

**Comment by escalade** [comment]
It compiles fine for me. libncurses is provided by netbsd-curses.

**Comment by FREEZX** [comment]
Oh sorry, forgot to mention i'm compiling for raspberry pi 1.
I'll try again and post results.

**Comment by FREEZX** [comment]
Yup, fresh git clone, fails with the same.

**Comment by escalade** [comment]
I'm building on Arch and it compiles fine for rpi2 which should be the same.

**Comment by FREEZX** [comment]
Could you try building for rpi?
I'm building on ubuntu, had success building two days ago

**Comment by efremov476** [comment]
Try remove htop in oem package

**Comment by FREEZX** [comment]
@yallah Of course that works, but it's not a solution to the root of the problem.

**Comment by ghost** [comment]
I am having the same issue. 

~~It appears that no package exists for libncurses.~~

EDIT: Found it in devel instead of escalade\depends.

**Comment by escalade** [comment]
Builds on Arch which is what I use, so closing.
