### ISSUE TITLE
Spotify Error

### ISSUE THREAD

**Issue by sirk123au** [escalade/LibreELEC.tv#25]
There is an error in /bin/spotify script not reading url correctly. from /tmp/spotify.log 
Sending action: Notification(Spotify,This is the first time you are starting Spotify. It is being downloaded in the background...,13000)
downloading http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.49.125.g72ee7853-${_amd64_pkgrel}_amd64.deb
wget: server returned error: HTTP/1.1 404 Not Found

Tried steps manually but i get a permission denied error.

**Comment by escalade** [comment]
This has been fixed.
