### ISSUE TITLE
lirc_serial module missing

### ISSUE THREAD

**Issue by jbollacke** [escalade/LibreELEC.tv#28]
The community edition is missing the lirc_serial module.

The module is present in LibreELEC 8.0.0.

```
LibreELEC:~ # modprobe lirc_serial
modprobe: FATAL: Module lirc_serial not found in directory /lib/modules/4.10.1
```

**Comment by escalade** [comment]
And this is needed for what exactly? There isn't any lirc serial module in 4.10 kernel, and it is not present in LE master.

**Comment by jbollacke** [comment]
Atric IR receiver

Looks like it was renamed to serial_ir: https://github.com/torvalds/linux/commit/fa5dc29c1fcc9151c3bcfd9e291a2899ae15f61

**Comment by jbollacke** [comment]
So it seems like this has to be fixed upstream.
