### ISSUE TITLE
Build fails on Samba

### ISSUE THREAD

**Issue by mlnlbrt** [escalade/LibreELEC.tv#30]
I'm trying to build the whole thing on clean Ubuntu 16.04 and it fails when building Samba:

` 
Checking for program python2.7-config                                             : /home/mln/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/bin/python-config 
/bin/sh: 1: /home/mln/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/bin/python-config: not found
`

I've changed 
`PYTHON_CONFIG="$SYSROOT_PREFIX/usr/bin/python-config`

to
`PYTHON_CONFIG="$ROOT/$TOOLCHAIN/bin/python-config`

in package.mk, but now I'm getting the following:

`Checking for custom code                                                          : Could not find the python development headers 
/home/mln/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/samba-4.5.5/wscript:107: error: the configuration failed (see '/home/mln/LibreELEC.tv/build.LibreELEC-Generic.x86_64-8.0-devel/samba-4.5.5/bin/config.log')
`

Any help?

**Comment by escalade** [comment]
My le8 branch (the one you were trying to build) hadn't been updated in a long while as I did my work in le8-test. Do a fresh clone and build again.
