### ISSUE TITLE
le82 - exfat-nofuse - compile for Odroid_C2

### ISSUE THREAD

**Issue by alegag** [escalade/LibreELEC.tv#34]
Hi,

  Trying to compile branch `le82` for `PROJECT=Odroid_C2 ARCH=aarch64`, when we get to the `exfat-nofuse` module, we can't go any further.

  We are met with a `unrecognised emulation mode: tune=cortex-a53` error message.

  If I try any of the suggested emulation mode, I get the same error message (with the `cortex-a53` part changing, of course).

  The command that fails is:
```
cd /usr/src/LibreELEC.tv/build.LibreELEC-Odroid_C2.aarch64-8.2-devel/exfat-nofuse-de4c760
/usr/src/LibreELEC.tv/build.LibreELEC-Odroid_C2.aarch64-8.2-devel/toolchain/bin/aarch64-libreelec-linux-gnueabi-ld -EL -march=armv8-a+crc+fp+simd -mtune=cortex-a53 -Wl,--as-needed -fuse-ld=gold -fuse-linker-plugin -flto=6 -r -o exfat.o exfat_core.o exfat_super.o exfat_api.o exfat_blkdev.o exfat_cache.o exfat_data.o exfat_bitmap.o exfat_nls.o exfat_oal.o exfat_upcase.o
```

  The command prior to that is (that generates the `.o` files to link):
```
make -C /usr/src/LibreELEC.tv/build.LibreELEC-Odroid_C2.aarch64-8.2-devel/linux-f6f2e4c M=/usr/src/LibreELEC.tv/build.LibreELEC-Odroid_C2.aarch64-8.2-devel/exfat-nofuse-de4c760 modules
```

  In the meantime, I'm trying to compile branch `le8` as this one doesn't depends on `exfat-nofuse`.

**Comment by escalade** [comment]
Odroid isn't supported in this project, only Generic/RPi2.
