### ISSUE TITLE
PS4 Controller Issue with Retroarch

### ISSUE THREAD

**Issue by Deus-Rex** [escalade/LibreELEC.tv#36]
Using latest image on RPi3, with a DS4 controller connected via bluetooth. Just recently got everything setup, and trying out the emulators.

Despite the PS4 controller connecting properly, and emulationstation being controlled fine, when I start a rom (SNES or GBA) the game won't accept any input. However, if I turn the controller off and on again, it works fine. Although the Retroarch menu doesn't seem to play well with it. I have to restart the controller to control the retroarch menu, and again when I go back to the game.

It also seems that I can't use the PS4 controller wired anywhere, not Kodi or ES, nevermind RA. What can I do to troubleshoot these issues? I've searched on the thread, but the folk with similar issues never came back with a solution from what I could tell.

**Comment by escalade** [comment]
I believe a couple fixed it by getting a new bluetooth dongle. I've seen similar reports on the RA forums as well, so I don't think it's build related.

**Comment by Deus-Rex** [comment]
Ah, that's a shame. Would have hoped the built-in bluetooth would have been adequate.

According to RA documentation, I'll have to look into using ds4drv
