### ISSUE TITLE
Build addon Makemkv 1.12.12 have an issue

### ISSUE THREAD

**Issue by Dainara82** [escalade/LibreELEC.tv#38]
while compiling the new version i get this error, whar can i do?

checking whether make supports nested variables... (cached) yes
checking whether ln -s works... yes
checking for pathconf... yes
checking for XAU... configure: error: Package requirements (xproto) were not met:

No package 'xproto' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables XAU_CFLAGS
and XAU_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by escalade** [comment]
You haven't included the full log. This is not an issue with the makemkv but rather a dependency problem in another package (xorgproto provides xproto).
