### ISSUE TITLE
RetroELEC support for the new ODROID-Go Super by Hardkernel?

### ISSUE THREAD

**Issue by Hedda** [escalade/LibreELEC.tv#46]
Hardkernel has announced ODROID-Go Super a few weeks ago and I believe that they offer samples to OS developers like you?

https://forum.odroid.com/viewtopic.php?f=187&t=41283&p=315650

It has the same Rockchip RK3326 internals as ODROID-Go Advance but comes with larger 5-inch 16:9 (FWVGA) square-pixel aspect radio screen with 854 x 480 pixels resolution, a higher capacity battery, and the addition of a second analog joystick and dedicated volume buttons.

https://github.com/hardkernel/linux/commits/odroidgoA-4.4.y

https://github.com/hardkernel/u-boot/commits/odroidgoA-v2017.09

PS: OGS also looks to be an offline device as it is without built-in WiFi but users can temporarily use an external USB WiFi dongle.

**Comment by escalade** [comment]
They didn't send me one, but I suppose I will add support sooner or later.
