### ISSUE TITLE
Packages from Lakka

### ISSUE THREAD

**Issue by RobLoach** [escalade/LibreELEC.tv#7]
[Lakka](http://www.lakka.tv/) provides some of the same packages. Are there any we could just inherit from it?
https://github.com/libretro/Lakka/tree/lakka/packages/libretro/
### Missing Systems

While we have no desire to be feature-complete, this is a list of systems that could be added to the fork.
- [x] Wonderswan: bettle-wswan
- [ ] Lynx: [handy](https://github.com/libretro/libretro-handy) https://github.com/escalade/LibreELEC.tv/pull/16
- [ ] [Lutro](https://github.com/libretro/libretro-lutro)
- [ ] PCFX: beetle-pcfx
- [ ] Sega 32X: picodrive
- [ ] Jaguar: virtualjaguar
- [ ] 3DO: 4DO

**Comment by escalade** [comment]
Yes, I based most of the libretro packages on the Lakka packages. Some are even straight copies.

**Comment by escalade** [comment]
I'm not aiming to be complete though, I just pick what I need/want.

**Comment by RobLoach** [comment]
> I just pick what I need/want.

Agreed, some cores are duplicates of systems. You've done a good job of picking the best ones.

**Comment by RobLoach** [comment]
Added a list of missing systems to the OP. 4DO, PicoDrive and Virtual Jaguar have been known to cause some issues, but the others are pretty solid. I'd like to see Wonderswan the most here.

**Comment by escalade** [comment]
Wonderswan was never even released outside of Japan, do you actually play these games? I would think the same games are available for mgba which is already packaged. Have you checked that it compiles for Generic/RPi2?

**Comment by RobLoach** [comment]
> Wonderswan was never even released outside of Japan, do you actually play these games?

There are a few hidden gems in the collection. A few years ago, I was playing through [Judgement Silversword](https://www.youtube.com/watch?v=RDp7xeEQbsQ).

> Have you checked that it compiles for Generic/RPi2?

RPi is what I'm most curious about. Would testing the RPi compilation work with the following?

```
platform=rpi1 scripts/build beetle-wswan
```

Is that a good way to test compiling for the Pi?

**Comment by escalade** [comment]
https://wiki.libreelec.tv/index.php?title=Compile

**Comment by RobLoach** [comment]
Nice job on Wonderswan! :+1:

**Comment by RobLoach** [comment]
Closing this one. Thanks a lot for keeping this going, Escalade! :+1:
